In [2]:
import numpy as np
import time

In [3]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
# performance difference between python list and np array

size = 1000000

#python list 
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f'python list time = {end-start} seconds')

#numpy arrays
np_arr = np.array(py_list)
start = time.time()
sq_arr = np_arr ** 2
end = time.time()
print(f'numpy array time = {end-start} seconds')

python list time = 0.1356515884399414 seconds
numpy array time = 0.005365610122680664 seconds


In [6]:
# creating numpy array - by list

arr = np.array([1,2,3,4,5])
print(arr, type(arr), arr.dtype, arr.shape)

arr2 = np.array([1,2,3,4,5,"shashi"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

arr3 = np.array([[1,2,3],[11,22,33],[1,2,3],[11,22,33]])
print(arr3, type(arr3), arr3.dtype, arr3.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'shashi'] <class 'numpy.ndarray'> <U21 (6,)
[[ 1  2  3]
 [11 22 33]
 [ 1  2  3]
 [11 22 33]] <class 'numpy.ndarray'> int64 (4, 3)


In [17]:
# creating numpy array 

arr4 = np.zeros((2,3), dtype = "int64")  #prefill zero #by default dtype=float
print(arr4, arr4.shape)

arr5 = np.ones((3,3))  #prefill one #by default dtype=float
print(arr5, arr5.shape)

arr6 = np.full((3,3), 10)  #prefill with value e.g=10 (here)
print(arr6, arr6.shape)

arr7 = np.eye(3,dtype = "int64")  #identity matrix #by default dtype=float
print(arr7, arr7.shape)

arr8 = np.arange(0,11,2) #range elements (start_val, end_val(not included),gap) 
print(arr8, arr8.shape)

arr9 = np.linspace(1,100,4) #evenly spaced arr (start_val, end_val, size_of_arr)
print(arr9, arr9.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (3, 3)
[[10 10 10]
 [10 10 10]
 [10 10 10]] (3, 3)
[[1 0 0]
 [0 1 0]
 [0 0 1]] (3, 3)
[ 0  2  4  6  8 10] (6,)
[  1.  34.  67. 100.] (4,)


In [31]:
# properties
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape)  # dimensions= m x n -(3,3)
print(arr.size)  # total elements -9
print(arr.dtype)  # data type - int64
print(arr.ndim)  # dimensions - 2

#changing dtype of array
float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [32]:
# Operations on np arrays

#1 reshaping
arr = np.array([[1,2,3],[4,5,6]])
print(arr, arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)

#2flattened
flattened = arr.flatten()
print(flattened, flattened.shape)


[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [30]:
#3 indexing 
arr = np.array([1,2,3,4,5,6])

print(arr[0])   
print(arr[4])

#4 fancy indexing   -> get value of all the indexes passed at a time 
idx = [0,1,3,4]
print(arr[idx])

#5 boolean indexing  -> getting all values which satisfies given condition 

print(arr[arr >= 2])
print(arr[arr%3 == 0])

1
5
[1 2 4 5]
[2 3 4 5 6]
[3 6]


In [29]:
#6 Slicing
arr = np.array([1,2,3,4,5])

print(arr[1:4:2])  #[start:end:step] # start is excluded
print(arr[1::2])
print(arr[::2])
print(arr[1:])

[2 4]
[2 4]
[1 3 5]
[2 3 4 5]


Python list slicing create copy of the original list.
But, 
Np array slicing just create the view of the original array.
Hence if we make any change in the sliced array it will be also changed in the original np array. (as shown below)

In [35]:
# slicing (view creation , not copy)
arr = np.array([1,2,3,4,5])
sub_arr = arr[1:3]
print(sub_arr)

sub_arr[0] = 200
print(sub_arr)
print(arr)

# to copy 
sub_arr = arr[1:3].copy

[2 3]
[200   3]
[  1 200   3   4   5]


In [41]:
# Data Types

arr = np.array([1,2,3,4,5, "shashi"])

print(arr , arr.dtype)

# Integer - int32 int64

# Floating number - float32, float64

# Boolean - bool

# Complex nums - complex64 complex128
arr1 = np.array([2 + 3j])
arr2 = np.array([5 + 4j])

print(arr1, arr2, arr1.dtype, arr1+arr2)

# String - S(byte-str) U(unicode-str)

# Object
arr3 = np.array(["shashi", {12,3,2,4}, 3.14])
print(arr3.dtype)

['1' '2' '3' '4' '5' 'shashi'] <U21
[2.+3.j] [5.+4.j] complex128 [7.+7.j]
object


In [43]:
# Axis in multi-dimensional array
# 2D_arrays :- axis 0 -> rows(vertically) , axis 1 -> columns(horizontally)
# 3D_arrays:- axis 0 -> depth/layer, axis 1-> rows, axis 2-> columns
 
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

print(arr2D[0:2 , 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [50]:
# 3D array

arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3D, arr3D.shape)

#indexing
print(arr3D[0,1,1])

#slicing
arr3D[:,0,:] = 100 # first row from both layer

print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
[[[100 100]
  [  3   4]
  [  5   6]]

 [[100 100]
  [  9  10]
  [ 11  12]]]


In [51]:
#vectorization 

arr = np.array([1,2,3,4,5])
print(arr ** 2)

arr2 = np.array([6,7,8,9,10])
print(arr + arr2)

[ 1  4  9 16 25]
[ 7  9 11 13 15]


In [57]:
#broadcasting

arr = np.array([1,2,3,4,5])
print(arr + 5) 

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr1+arr2)

arr1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
# print(arr1+arr2)  
#will show error(cause broadcast only if one of the dimension is 1)
print(arr1.shape)
print(arr2.shape)

[ 6  7  8  9 10]
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]
(2, 5)
(3, 5)


In [ ]:
# Normalization

In [65]:
# mathematical function
arr = np.array([1,2,3,4,5])

#aggregation

print(arr.sum())
print(arr.prod())
print(arr.min())
print(arr.max())
print(arr.argmin())  # idx of min ele 
print(arr.argmax())  # idx of max ele

print(np.mean(arr))
print(np.std(arr))   # standard deviation
print(np.median(arr))
print(np.var(arr))   # varience

# power fxn

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr , 3))

# log

print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

# rounding off
print(np.round(4.21))
print(np.ceil(4.21))  # upper bound
print(np.floor(4.21)) # lower bound
print(np.trunc(4.21))  # removes decimal value

arr = np.array([1,2,3,-8,4,5,-3,1,4])

print(np.unique(arr))
print(np.sort(arr))

print(np.abs(arr))   # make positive of negative 

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
4.0
5.0
4.0
4.0
[-8 -3  1  2  3  4  5]
[-8 -3  1  1  2  3  4  4  5]
[1 2 3 8 4 5 3 1 4]
